name: e_commerce
description: "E-commerce is an application built to provide users with an easy,
  secure and fast experience when shopping online."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_rating_bar: ^4.0.1
  formz: ^0.8.0
  # freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  readmore: ^3.0.0
  retrofit: ^4.4.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9

flutter_gen:
  output: lib/generated/assets

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - .env

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Thin.otf
          weight: 100
        - asset: assets/fonts/metropolis/Metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/metropolis/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/metropolis/Metropolis-Black.otf
          weight: 900
